---
title: "Suicide Rates Visualization Project"
author: 'Hamed Vaheb, Elnaz Khaveh'
date: '01 Dec 2021'
output:
  html_document:
    number_sections: true
    toc: true
    code_folding: "hide"
    theme: readable
    highlight: haddock
---

```{r message = FALSE, warning = FALSE}
library(tidyverse) # general
library(ggalt) # dumbbell plots
library(countrycode) # continent
library(rworldmap) # quick country-level heat maps
library(gridExtra) # plots
library(broom) # significant trends within countries

theme_set(theme_light())

```

# **Introduction**
We have used the [suicide rates dataset](https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016). 


## **Import and Cleaning**


```{r}

# 1) Import

data <- read_csv("dataset/master.csv") 

# rename columns

data <- data %>% 
  select(-c(`HDI for year`, `suicides/100k pop`)) %>%
  rename(gdp_for_year = `gdp_for_year ($)`, 
         gdp_per_capita = `gdp_per_capita ($)`, 
         country_year = `country-year`) %>%
  as.data.frame()
  
  glimpse(data)
```

